server:
  port: 7107
spring:
  application:
    name: wm-virtual-construction
  datasource:
    url: jdbc:mysql://192.168.10.201:3306/wm-virtual-construction?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: yg987654321
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
