uploadPath: E:/upload/file/
accessPath: /file/
server:
  port: 7111
  tomcat:
          basedir: E:/upload/temp
spring:
  application:
    name: wm-document
  datasource:
    url: jdbc:mysql://192.168.10.201:3306/wm_file_share?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: yg987654321
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
