server:
  port: 7108
  tomcat:
    basedir: D:/tempUpload
spring:
  application:
    name: wm-quality
  datasource:
    url: jdbc:mysql://192.168.10.201:3306/wm-quality?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: yg987654321
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB