FWCQExcelModelPath: E:\ExcelModel\HDExport.xlsx
ZBFXExcelModelPath: E:\ExcelModel\PPRExport.xlsx
GXGYExcelModelPath: E:\ExcelModel\PLTExport.xlsx
JTDGExcelModelPath: E:\ExcelModel\TDExport.xlsx
server:
  port: 7106
spring:
  application:
    name: wm-prophase-eng
  datasource:
    url: jdbc:mysql://192.168.10.201:3306/wm-prophase-eng?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: yg987654321
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
